### ISSUE TITLE
Add `auctionStartDate`/`startDate` to `FairSale` contract

### ISSUE THREAD

**Issue by adamazad** [cryptonative-ch/mesa-smartcontracts#106]
The sale starts upon deploying the contract. Which isn't ideal.

**Comment by denciu** [comment]
This issue overlaps with [this](https://github.com/cryptonative-ch/mesa-interface/issues/341). We need to get in touch with @nicoelzer to make sure he's not working on it (I doubt but you know...) :D

**Comment by nicoelzer** [comment]
@denciu not working on this.

**Comment by denciu** [comment]
Resolved by #130
