### ISSUE TITLE
AuctionLauncher.getTemplate returns EasyAcution instead of EasyAuctionTemplate 

### ISSUE THREAD

**Issue by adamazad** [cryptonative-ch/mesa-smartcontracts#39]
**Describe the bug**
`AuctionLauncher.getTemplate` returns the address of an `EasyAuction`

**To Reproduce**
1. Go to [AuctionLauncher on Rinkeby](https://rinkeby.etherscan.io/address/0x031053f28bf9273b96f7d0dcd20e970ee3bbb54f#readContract)
2. Call `getTemplate` with parameter 1 (the templateId of EasyAuction). 
3. Click on the address.

**Expected behavior**
It should return the `EasyAuctionTemplate` contract.

**Screenshots**

**Comment by nicoelzer** [comment]
Hey @adamazad this is the expected behavior.

On the auctionLauncher the template is called `EasyAuction`, while on the templateLauncher it's called `EasyAuctionTemplate`

**Comment by martinkrung** [comment]
@nicoelzer close this?
