### ISSUE TITLE
Add template name to the contract as constant

### ISSUE THREAD

**Issue by adamazad** [cryptonative-ch/mesa-smartcontracts#41]
**Describe the solution you'd like**

Adding a constant string variable in the template contract.

## Possible Implementation

```solidity
contract EasyAuctionTemplate {
    string constant name = "EasyAuction"; 
}
```

**Additional context**

To determine whether to create a new `EasyAuction` or `FixedPriceAuction`, the name helps. 

![image](https://user-images.githubusercontent.com/1926216/111901552-f9048200-8a49-11eb-8476-a00ece9da474.png)

**Comment by nicoelzer** [comment]
@adamazad implemented with this commit: https://github.com/cryptonative-ch/mesa-smartcontracts/commit/5c8aa6726ccbb083fdfdf71cbbd8ab432a23bd41
