### ISSUE TITLE
minBuyAmount for Fairsale?

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-smartcontracts#56]
minBuyAmount - we don't have this:

https://github.com/gnosis/ido-contracts/blob/main/contracts/EasyAuction.sol

![Screenshot at 2021-04-17 19-06-07](https://user-images.githubusercontent.com/918180/115120878-10cf1780-9fb0-11eb-93f8-536ca17dcdec.png)

I did see this working on the clearingpricecalc in the FE, there minBuyAmount is needed to make a price floor, if not enough bids

https://github.com/cryptonative-ch/mesa-smartcontracts/blob/develop/contracts/sales/FairSale.sol#L74

**Comment by denciu** [comment]
It's no longer valid, take a look at https://github.com/cryptonative-ch/mesa-smartcontracts/blob/6fa661846fc29432ef03feabe662e97e654bd600/contracts/sales/FairSale.sol#L83 . Closing this issue
