### ISSUE TITLE
Send back stuck token

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-smartcontracts#57]
Every contract should have the  possibility to send back funds if somebody mistakenly sends token to the contract. Best would be to take a 10% haircut because such things should have a price attached. Send the 10% fee to the fee address.

**Describe the solution you'd like**

Refund function which sends token back to the sender. It has to be called by the sender. If somebody sends token from a CEX this will not work. For CEX sends,  ownership can't be proven, so sending back is not fraud proof. This kind of stuck token should be sent 100% forward to the fee address from time to time. This forward function should only be called by a configured address.

**Describe alternatives you've considered**
Not doing this, but we know this will happen.

**Additional context**
There may be a well tested code for this out there.

**Comment by nicoelzer** [comment]
Hey @martinkrung, 

current implementation of this, here:

- https://github.com/cryptonative-ch/mesa-smartcontracts/blob/develop/contracts/sales/FixedPriceSale.sol#L309
- https://github.com/cryptonative-ch/mesa-smartcontracts/blob/develop/contracts/sales/FixedPriceSale.sol#L316
