### ISSUE TITLE
have startDate/endDate for fairSale, no duration!

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-smartcontracts#61]
Start of a sale can't be in the future right now, becaus as soon as tx is done, sale starts

**Describe the solution you'd like**

Have startDate/endDate  like in fixedprice sale! 

![Screenshot at 2021-05-13 18-03-13](https://user-images.githubusercontent.com/918180/118153099-c8bbdd00-b415-11eb-8ca9-a49cb153275c.png)

https://github.com/cryptonative-ch/mesa-smartcontracts/blob/d41eac1ec4a80f7decf24b5b88e3169de16210b1/contracts/sales/FairSale.sol#L133

**Describe alternatives you've considered**

## Possible Implementation
Look how its done in fixedprice sale

**Comment by denciu** [comment]
Resolved by #130
