### ISSUE TITLE
hardcoded minimumBiddingAmountPerOrder is too low

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-smartcontracts#62]
I don't know if we should hard-code this and if yes, minimumBiddingAmountPerOrder is way too low, this is only dust. (This depends on the decimal of the ERC-20 token)  

If decimal 18, then 100 would be ~0.0000000000000001!

https://github.com/cryptonative-ch/mesa-smartcontracts/blob/1ead2daa4510d21fd0e4321f2dbc12345e16af90/contracts/templates/FairSaleTemplate.sol#L60

`uint256 minimumBiddingAmountPerOrder = 100;`

![Screenshot at 2021-05-13 19-05-17](https://user-images.githubusercontent.com/918180/118160135-37049d80-b41e-11eb-98c3-5d1771184c28.png)

**Comment by martinkrung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hardcoded value to low:](https://trello.com/c/UqbVwhvw/145-hardcoded-value-to-low)

**Comment by denciu** [comment]
Default value is no longer provided therefore closing this issue.
