### ISSUE TITLE
templatedeployer -> templateDeployer

### ISSUE THREAD

**Issue by martinkrung** [cryptonative-ch/mesa-smartcontracts#77]

**Comment by martinkrung** [comment]
https://github.com/cryptonative-ch/mesa-smartcontracts/commit/48627ca58b39b541b1aa0bac6bc23bfbf6bcbdf5

![Screenshot at 2021-06-21 16-24-30.png](https://images.zenhubusercontent.com/60b4b16674cd33c6c7c4952c/0167cd98-e823-4c3f-94f2-6c2fb5daf011)

**Comment by nicoelzer** [comment]
Closed by https://github.com/cryptonative-ch/mesa-smartcontracts/commit/bf9b6b99dbe73314e91a02a9d534d8a838e634ed
